//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Configuration;
using System;

namespace NHapi.Base.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        public static string ConnectionString
        {
            get
            {

                string val = ConfigurationManager.AppSettings["Hl7ConnectionString"];
                if (val == null)
                    throw new ApplicationException("You must specify the Hl7ConnectionString in the config file");
                return val;
            }
        }

        public static bool UseFactory
        {
            get
            {

                string val = ConfigurationManager.AppSettings["UseFactory"];
                if (val == null)
                    throw new ApplicationException("You must specify the UseFactory in the config file");
                return Convert.ToBoolean(val);
            }
        }
    }
}
