//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Configuration;

namespace ca.uhn.Properties 
{
    
    
	internal sealed class Settings 
	{
        
		private static Settings _settings = new Settings();
		public static Settings Default
		{
			get
			{
				return _settings;
			}
		}

		public string ConnectionString
		{
			get{ return ConfigurationSettings.AppSettings["ConnectionString"].ToString();}
		}

		public bool useFactory 
		{
			get 
			{
				return (Convert.ToBoolean((ConfigurationSettings.AppSettings["useFactory"])));
			}
		}
	}
}
